export interface WordPair {
  original: string;
  correct: string | string[];
  multiAnagram?: boolean;
}

// Source: next-project/kod-09-main/components/anagram-trainer.tsx (ported)
export const TASKS: Record<number, WordPair[]> = {
  1: [
    { original: "АКР", correct: "РАК" },
    { original: "БУК", correct: "КУБ" },
    { original: "ДОГ", correct: "ГОД" },
    { original: "КИТ", correct: "ТИК" },
    { original: "ОПТ", correct: "ПОТ" },
    { original: "ВОЗ", correct: "ЗОВ" },
  ],
  2: [
    { original: "НОС", correct: "СОН" },
    { original: "ЛАЗ", correct: "ЗАЛ" },
    { original: "РОВ", correct: "ВОР" },
    { original: "ВЕС", correct: "СЕВ" },
    { original: "АКТ", correct: "ТАК" },
    { original: "ИКС", correct: "КИС" },
  ],
  3: [
    { original: "ВХОД", correct: "ВДОХ" },
    { original: "АНИС", correct: "САНИ" },
    { original: "АРФА", correct: "ФАРА" },
    { original: "БАНЯ", correct: "БАЯН" },
    { original: "АРГО", correct: "ГОРА" },
    { original: "ЖАЛО", correct: "ЛОЖА" },
  ],
  4: [
    { original: "ИГЛА", correct: "ЛИГА" },
    { original: "КАНТ", correct: "ТАНК" },
    { original: "ЛИСА", correct: "СИЛА" },
    { original: "МАЯК", correct: "ЯМКА" },
    { original: "МАТЬ", correct: "ТЬМА" },
    { original: "ПИОН", correct: "ПОНИ" },
  ],
  5: [
    { original: "УГАР", correct: "РАГУ" },
    { original: "РУДА", correct: "УДАР" },
    { original: "УЛАН", correct: "ЛУНА" },
    { original: "УШАТ", correct: "ТУША" },
    { original: "ХАОС", correct: "СОХА" },
    { original: "КУСТ", correct: "СТУК" },
  ],
  6: [
    { original: "ШАРФ", correct: "ФАРШ" },
    { original: "АРАП", correct: "ПАРА" },
    { original: "БРАК", correct: "КРАБ" },
    { original: "БРИГ", correct: "ГРИБ" },
    { original: "БРОМ", correct: "РОМБ" },
    { original: "БРУС", correct: "СРУБ" },
  ],
  7: [
    { original: "БЯЗЬ", correct: "ЗЯБЬ" },
    { original: "ВЕСТ", correct: "СВЕТ" },
    { original: "ВРАЧ", correct: "РВАЧ" },
    { original: "БРЕГ", correct: "ГЕРБ" },
    { original: "ГРОТ", correct: "ТОРГ" },
    { original: "ДОКА", correct: "КОДА" },
  ],
  8: [
    { original: "ДОЯР", correct: "ЯДРО" },
    { original: "ЖАКО", correct: "КОЖА" },
    { original: "КАРП", correct: "ПАРК" },
    { original: "КЛЁШ", correct: "ШЁЛК" },
    { original: "КУМА", correct: "МУКА" },
    { original: "МАРС", correct: "СРАМ" },
  ],
  9: [
    { original: "НАСТ", correct: "СТАН" },
    { original: "НИВА", correct: "ВИНА" },
    { original: "ТЕЛО", correct: "ЛЕТО" },
    { original: "ТАЛЬ", correct: "АЛЬТ" },
    { original: "ЛОЖА", correct: "ЖАЛО" },
    { original: "СЕРП", correct: "ПЕРС" },
  ],
  10: [
    { original: "КАРЕ", correct: "РЕКА" },
    { original: "СОЛЬ", correct: "ЛОСЬ" },
    { original: "ЛОЗА", correct: "ЗОЛА" },
    { original: "СТОП", correct: "ПОСТ" },
    { original: "КОРТ", correct: "КРОТ" },
    { original: "УРОК", correct: "УКОР" },
  ],
  11: [
    { original: "УРОН", correct: "РУНО" },
    { original: "НИША", correct: "ШИНА" },
    { original: "АМБАР", correct: "АМБРА" },
    { original: "АВАНС", correct: "САВАН" },
    { original: "АВРАЛ", correct: "ЛАВРА" },
    { original: "АТЛАС", correct: "САЛАТ" },
  ],
  12: [
    { original: "АДРЕС", correct: "СРЕДА" },
    { original: "АМПИР", correct: "ПРИМА" },
    { original: "АНГАР", correct: "НАГАР" },
    { original: "АНОНС", correct: "НАНОС" },
    { original: "АОРТА", correct: "ОТАРА" },
    { original: "АПОРТ", correct: "ТРОПА" },
  ],
  13: [
    { original: "АРКАН", correct: "РАНКА" },
    { original: "БАНКА", correct: "КАБАН" },
    { original: "БАРЖА", correct: "ЖАБРА" },
    { original: "БАРОН", correct: "НАБОР" },
    { original: "БАЧОК", correct: "БОЧКА" },
    { original: "БИРЮК", correct: "БРЮКИ" },
  ],
  14: [
    { original: "БОИНГ", correct: "БИНГО" },
    { original: "БОКАЛ", correct: "КОЛБА" },
    { original: "ГЛАВА", correct: "ВЛАГА" },
    { original: "ВАЛКА", correct: "ЛАВКА" },
    { original: "ВАРАН", correct: "НАВАР" },
    { original: "ВРАТА", correct: "ТРАВА" },
  ],
  15: [
    { original: "ВЕДРО", correct: "ДРЕВО" },
    { original: "ВИОЛА", correct: "ОЛИВА" },
    { original: "ВОЛАН", correct: "ВОЛНА" },
    { original: "ВЫХОД", correct: "ВЫДОХ" },
    { original: "ВОБЛА", correct: "ОБВАЛ" },
    { original: "ВОЛОС", correct: "СЛОВО" },
  ],
  16: [
    { original: "ВАЛИК", correct: "ВИЛКА" },
    { original: "ВЫВОЗ", correct: "ВЫЗОВ" },
    { original: "ВЫБОР", correct: "ОБРЫВ" },
    { original: "ВЕСНА", correct: "НАВЕС" },
    { original: "ГРОЗА", correct: "РОЗГА" },
    { original: "ВАЛОК", correct: "ВОКАЛ" },
  ],
  17: [
    { original: "ДЕБРИ", correct: "ДЕРБИ" },
    { original: "ДЕКОР", correct: "КРЕДО" },
    { original: "ДИСКО", correct: "ОКСИД" },
    { original: "БОРДО", correct: "ДОБРО" },
    { original: "ДОМРА", correct: "МОРДА" },
    { original: "РОНДО", correct: "ДОНОР" },
  ],
  18: [
    { original: "ДЫРКА", correct: "КАДРЫ" },
    { original: "ЗАБОР", correct: "ОБРАЗ" },
    { original: "ЗАГОН", correct: "ГАЗОН" },
    { original: "ЗАМОК", correct: "МАЗОК" },
    { original: "ЗЕРНО", correct: "РЕЗОН" },
    { original: "ИСТОК", correct: "КОСТИ" },
  ],
  19: [
    { original: "КАГОР", correct: "ГОРКА" },
    { original: "КАНАТ", correct: "НАКАТ" },
    { original: "КАПОТ", correct: "ТОПКА" },
    { original: "КАРАТ", correct: "КАРТА" },
    { original: "КУЛАК", correct: "КУКЛА" },
    { original: "КОРМА", correct: "КОМАР" },
  ],
  20: [
    { original: "КАМЫШ", correct: "МЫШКА" },
    { original: "КОЛБА", correct: "БОКАЛ" },
    { original: "КРУЧА", correct: "РУЧКА" },
    { original: "КРЕСТ", correct: "ТРЕСК" },
    { original: "КРЫСА", correct: "РЫСАК" },
    { original: "КАПОР", correct: "ПОРКА" },
  ],
  21: [
    { original: "ЛАСКА", correct: "СКАЛА" },
    { original: "ЛАКЕЙ", correct: "ЛЕЙКА" },
    { original: "ЛАПТА", correct: "ПЛАТА" },
    { original: "ЛИДЕР", correct: "ДИЛЕР" },
    { original: "ЛИМАН", correct: "НАЛИМ" },
    { original: "МАГМА", correct: "ГАММА" },
  ],
  22: [
    { original: "МАЙКА", correct: "КАЙМА" },
    { original: "МАКСИ", correct: "МИСКА" },
    { original: "МАСЛО", correct: "СМОЛА" },
    { original: "НАСОС", correct: "СОСНА" },
    { original: "НАВОЗ", correct: "ВАЗОН" },
    { original: "НОРОВ", correct: "ВОРОН" },
  ],
  23: [
    { original: "НОРМА", correct: "РОМАН" },
    { original: "НОЧКА", correct: "КОЧАН" },
    { original: "НАКАЛ", correct: "КАНАЛ" },
    { original: "ОТВЕС", correct: "СОВЕТ" },
    { original: "ОБРОК", correct: "КОРОБ" },
    { original: "ОКЛАД", correct: "ЛОДКА" },
  ],
  24: [
    { original: "ОТРОК", correct: "РОКОТ" },
    { original: "ПРОСО", correct: "ОПРОС" },
    { original: "ПРАВО", correct: "ПОВАР" },
    { original: "ЛАПТИ", correct: "ПЛИТА" },
    { original: "ПЛЕСК", correct: "СКЛЕП" },
    { original: "РАНЕТ", correct: "РЕНТА" },
  ],
  25: [
    { original: "РУБКА", correct: "БУРКА" },
    { original: "РИФМА", correct: "ФИРМА" },
    { original: "СУКНО", correct: "КОНУС" },
    { original: "СОКОЛ", correct: "КОЛОС" },
    { original: "САДОК", correct: "ДОСКА" },
    { original: "САМБА", correct: "БАСМА" },
  ],
  26: [
    { original: "СПРУТ", correct: "СТРУП" },
    { original: "САЙРА", correct: "САРАЙ" },
    { original: "САМКА", correct: "МАСКА" },
    { original: "СИТЕЦ", correct: "ИСТЕЦ" },
    { original: "СТЕНА", correct: "СЕНАТ" },
    { original: "ТОРБА", correct: "ТАБОР" },
  ],
  27: [
    { original: "ТЁРКА", correct: "АКТЁР" },
    { original: "ХАЛВА", correct: "ХВАЛА" },
    { original: "ЧАСОК", correct: "САЧОК" },
    { original: "ЧУРКА", correct: "РУЧКА" },
    { original: "ЧУЛОК", correct: "ЛУЧОК" },
    { original: "ШПАЛА", correct: "ЛАПША" },
  ],
  28: [
    { original: "ШАКАЛ", correct: "ШКАЛА" },
    { original: "ШАРИК", correct: "РИКША" },
    { original: "АЗБУКА", correct: "БАЗУКА" },
    { original: "АМПЛУА", correct: "АМПУЛА" },
    { original: "АПЛОМБ", correct: "ПЛОМБА" },
    { original: "АРНИКА", correct: "ИРАНКА" },
  ],
  29: [
    { original: "АТЛАНТ", correct: "ТАЛАНТ" },
    { original: "БЕЛЬМО", correct: "БЕМОЛЬ" },
    { original: "ВЕРСТА", correct: "СТЕРВА" },
    { original: "ГРАНАТ", correct: "ГАРАНТ" },
    { original: "ДЕТАЛЬ", correct: "ДЕЛЬТА" },
    { original: "ДРОТИК", correct: "ДИКТОР" },
  ],
  30: [
    { original: "ЕЛЬНИК", correct: "НИКЕЛЬ" },
    { original: "ИГОЛКА", correct: "ЛОГИКА" },
    { original: "КАПРИЗ", correct: "ПРИКАЗ" },
    { original: "КАРИЕС", correct: "СЕКИРА" },
    { original: "КВИНТА", correct: "ВАТНИК" },
    { original: "КОРВЕТ", correct: "ВЕКТОР" },
  ],
  31: [
    { original: "КРАСКА", correct: "КАРКАС" },
    { original: "КОРСЕТ", correct: "СЕКТОР" },
    { original: "КОРШУН", correct: "ШНУРОК" },
    { original: "ЛОПАТА", correct: "ОПЛАТА" },
    { original: "МОЛЬБА", correct: "АЛЬБОМ" },
    { original: "ПАЛЬТО", correct: "ЛАПОТЬ" },
  ],
  32: [
    { original: "ПОТЕХА", correct: "ПЕХОТА" },
    { original: "ПЛАНКА", correct: "КЛАПАН" },
    { original: "ПЛЮШКА", correct: "ШЛЮПКА" },
    { original: "ПОГРЕБ", correct: "ПРОБЕГ" },
    { original: "ПУДЕЛЬ", correct: "ДУПЕЛЬ" },
    { original: "РАБЫНЯ", correct: "БАРЫНЯ" },
  ],
  33: [
    { original: "СТИРКА", correct: "СТАРИК" },
    { original: "УБОРКА", correct: "КОБУРА" },
    { original: "ЦОКОЛЬ", correct: "КОЛЬЦО" },
    { original: "ЭТАНОЛ", correct: "ЭТАЛОН" },
    { original: "АДАПТЕР", correct: "ПЕТАРДА" },
    { original: "БАРСТВО", correct: "РАБСТВО" },
  ],
  34: [
    { original: "БЕЛОРУС", correct: "ЛЕСОРУБ" },
    { original: "ВЕЛИКАН", correct: "ВАЛЕНКИ" },
    { original: "ВОДОПАД", correct: "ПОДВОДА" },
    { original: "ЗАМЕТКА", correct: "КАЗЕМАТ" },
    { original: "ЗАРНИЦА", correct: "РАЗНИЦА" },
    { original: "КОЧЕРГА", correct: "КОЧЕГАР" },
  ],
  35: [
    { original: "МАНИШКА", correct: "МАШИНКА" },
    { original: "МОШКАРА", correct: "РОМАШКА" },
    { original: "МЕТРИКА", correct: "МАТЕРИК" },
    { original: "ПЕТЛИЦА", correct: "ТЕПЛИЦА" },
    { original: "РЕНЕГАТ", correct: "РЕАГЕНТ" },
    { original: "РОСИНКА", correct: "СОРИНКА" },
  ],
  36: [
    { original: "ТОРНАДО", correct: "РОТОНДА" },
    { original: "ТРИБУНА", correct: "ТУРБИНА" },
    { original: "ВЕРНОСТЬ", correct: "РЕВНОСТЬ" },
    { original: "КАРАТИСТ", correct: "АРТИСТКА" },
  ],
  37: [
    { original: "БАР", correct: ["РАБ", "БРА"], multiAnagram: true },
    { original: "КОТ", correct: ["ТОК", "КТО"], multiAnagram: true },
    { original: "РАЖ", correct: ["РЖА", "ЖАР"], multiAnagram: true },
    { original: "ВОИН", correct: ["ВИНО", "ОВИН"], multiAnagram: true },
    { original: "АРАБ", correct: ["АРБА", "РАБА"], multiAnagram: true },
    { original: "МАРШ", correct: ["ШРАМ", "ШАРМ"], multiAnagram: true },
  ],
  38: [
    { original: "АРКА", correct: ["КАРА", "РАКА"], multiAnagram: true },
    { original: "ДУРА", correct: ["РУДА", "УДАР"], multiAnagram: true },
    { original: "ИНОК", correct: ["КОНИ", "КИНО"], multiAnagram: true },
    { original: "РАУТ", correct: ["ТУРА", "РУТА"], multiAnagram: true },
    { original: "ТОРФ", correct: ["ФТОР", "ФОРТ"], multiAnagram: true },
    { original: "УРАН", correct: ["УРНА", "РУНА"], multiAnagram: true },
  ],
  39: [
    { original: "АНКЕР", correct: ["НЕРКА", "КЕНАР"], multiAnagram: true },
    { original: "КАЗАН", correct: ["НАКАЗ", "КАЗНА"], multiAnagram: true },
    { original: "КОРАН", correct: ["КРОНА", "НОРКА"], multiAnagram: true },
    { original: "МАРКА", correct: ["РАМКА", "КАРМА"], multiAnagram: true },
    { original: "НОСИК", correct: ["НОСКИ", "ОНИКС"], multiAnagram: true },
    { original: "ПЯТАК", correct: ["ТЯПКА", "ПЯТКА"], multiAnagram: true },
  ],
  40: [
    { original: "ТУШКА", correct: ["ШТУКА", "ШУТКА"], multiAnagram: true },
    { original: "ТОПОР", correct: ["РОПОТ", "ОТПОР"], multiAnagram: true },
    { original: "ЛИСТОК", correct: ["СТОЛИК", "СЛИТОК"], multiAnagram: true },
    { original: "МОСТКИ", correct: ["МОСТИК", "МОСКИТ"], multiAnagram: true },
    { original: "НЕМОТА", correct: ["МОНЕТА", "ОТМЕНА"], multiAnagram: true },
    { original: "ПОРТИК", correct: ["ТРОПИК", "ПРИТОК"], multiAnagram: true },
  ],
  41: [
    { original: "РАКЕТА", correct: ["КАРЕТА", "КАРАТЕ"], multiAnagram: true },
    { original: "РОСТ", correct: ["СОРТ", "ТРОС", "ТОРС"], multiAnagram: true },
    { original: "АСКЕТ", correct: ["СЕТКА", "СЕКТА", "ТЕСАК"], multiAnagram: true },
    { original: "КЛОУН", correct: ["КОЛУН", "КУЛОН", "УКЛОН"], multiAnagram: true },
    { original: "АВТОР", correct: ["ТОВАР", "ОТВАР", "ТАВРО", "РВОТА"], multiAnagram: true },
  ],
};

